-- HLOI Defines

NDefines_Graphics.NGraphics.COUNTRY_COLOR_HUE_MODIFIER = 0.0
NDefines_Graphics.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 0.8
NDefines_Graphics.NGraphics.COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 1
NDefines_Graphics.NGraphics.COUNTRY_UI_COLOR_HUE_MODIFIER = 0.0
NDefines_Graphics.NGraphics.COUNTRY_UI_COLOR_SATURATION_MODIFIER = 1.2
NDefines_Graphics.NGraphics.COUNTRY_UI_COLOR_BRIGHTNESS_MODIFIER = 1.2
	